<form method="post" class="form-horizontal">
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">
            Name
        </label>
        <div class="col-sm-10">
            <input
                type="text"
                class="form-control"
                name="name"
                id="name"
                value="Chris Young"
            >
        </div>
    </div>
    <div class="form-group">
        <label for="position" class="col-sm-2 control-label">
            Position
        </label>
        <div class="col-sm-10">
            <input
                type="text"
                class="form-control"
                name="position"
                id="position"
                value="Outfielder"
            >
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            League
        </label>
        <div class="col-sm-10">
            <div class="radio">
                <label>
                    <input type="radio" name="league" id="american" value="american" checked>
                    American
                </label>
            </div>
            <div class="radio">
                <label>
                    <input type="radio" name="league" value="national">
                    National
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="team_id" class="col-sm-2 control-label">
            Team
        </label>
        <div class="col-sm-10">
            <select name="team_id" id="team_id" class="form-control">
                <option value="1">Red Sox</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true">
                </span>
                Save
            </button>
        </div>
    </div>
</form>