<div class="form-group">
    <label for="name" class="col-sm-2 control-label">
        Name
    </label>
    <div class="col-sm-10">
        <input
            type="text"
            class="form-control"
            name="name"
            id="name"
            placeholder="Texas Rangers"
        >
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        League
    </label>
    <div class="col-sm-10">
        <div class="radio">
            <label>
                <input type="radio" name="league" value="american" checked>
                American
            </label>
        </div>
        <div class="radio">
            <label>
                <input type="radio" name="league" value="national">
                National
            </label>
        </div>
    </div>
</div>
<div class="form-group">
    <label for="stadium" class="col-sm-2 control-label">
        Stadium
    </label>
    <div class="col-sm-10">
        <input
            type="text"
            class="form-control"
            name="stadium"
            id="stadium"
            placeholder="Globe Life Park"
        >
    </div>
</div>